name: DevSecOps Pipeline - Semgrep SAST

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  security:
    name: Semgrep SAST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep (JSON + text)
        run: |
          # Exécution avec ton fichier de règles personnalisé
          semgrep --config=.semgrep/java-password-sql.yml --json -o semgrep-report.json || true
          semgrep --config=.semgrep/java-password-sql.yml --text -o semgrep-report.txt || true
          echo "✅ Semgrep terminé. Rapports générés : semgrep-report.json / semgrep-report.txt"

      - name: Fail pipeline if Semgrep found issues
        run: |
          if [ -f semgrep-report.json ] && grep -q '"check_id"' semgrep-report.json; then
            echo "❌ Vulnérabilités détectées par Semgrep !"
            echo "➡️ Voir semgrep-report.txt et semgrep-report.json pour les détails."
            exit 1
          else
            echo "✅ Aucun problème détecté par Semgrep."
          fi

      - name: Upload Semgrep reports
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: |
            semgrep-report.json
            semgrep-report.txt
